#include "codegen.h"
#include <iostream>

void CodeGenerator::writeIndent() {
    for (int i = 0; i < currentIndent; i++) {
        outFile << "    "; // 4 spaces per indent level
    }
}

void CodeGenerator::generate(const ProgramNode* program, const std::string& outputFilename) {
    outFile.open(outputFilename);
    if (!outFile.is_open()) {
        throw std::runtime_error("Code Generator Error: Could not create output file.");
    }

    // 1. Write the C++ Boilerplate
    outFile << "// Automatically generated by Team RS Compiler\n";
    outFile << "#include <iostream>\n\n";
    outFile << "#include <string>\n\n";
    outFile << "int main() {\n";

    // 2. Translate every node in the AST
    for (const auto& stmt : program->statements) {
        generateNode(stmt.get());
    }

    // 3. Close the main function
    outFile << "\n    return 0;\n";
    outFile << "}\n";

    outFile.close();
}

void CodeGenerator::generateNode(const ASTNode* node) {
    if (!node) return;

    if (auto v = dynamic_cast<const VarDeclNode*>(node)) {
        writeIndent();
        if (v->hasInitialValue) {
            outFile << v->type << " " << v->varName << " = " << v->initialValue << ";\n";
        } else {
            outFile << v->type << " " << v->varName << ";\n";
        }
    }
    
    else if (auto a = dynamic_cast<const AssignmentNode*>(node)) {
        writeIndent();
        outFile << a->varName << " = " << a->value << ";\n";
    }
    
    else if (auto p = dynamic_cast<const PrintNode*>(node)) {
        writeIndent();
        outFile << "std::cout << " << p->varName << " << std::endl;\n";
    }
    
    else if (auto i = dynamic_cast<const IfNode*>(node)) {
        writeIndent();
        outFile << "if (" << i->conditionVar << " > " << i->conditionValue << ") {\n";
        
        currentIndent++; // Increase indent for the code inside the IF
        generateNode(i->action.get());
        currentIndent--; // Decrease indent after
        
        writeIndent();
        outFile << "}\n";
    }
    
    else if (auto r = dynamic_cast<const RepeatNode*>(node)) {
        writeIndent();
        // Generate a standard C++ for-loop
        // We use a unique loop variable name just in case loops are nested later
        std::string loopVar = "i_loop"; 
        outFile << "for (int " << loopVar << " = 0; " << loopVar << " < " << r->count << "; " << loopVar << "++) {\n";
        
        currentIndent++; // Increase indent for the code inside the Loop
        generateNode(r->action.get());
        currentIndent--; // Decrease indent after
        
        writeIndent();
        outFile << "}\n";
    }
}